// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import {Component, OnInit} from '@angular/core';
import {Livro} from "../livro";
import {ControleEditoraService} from "../controle-editora.service";
import {ControleLivrosService} from "../controle-livros.service";
import {Editora} from "../editora";
import {Router} from "@angular/router";

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent implements OnInit{
  livro : Livro;
  autoresForm: string = '';
  public editoras:Array<Editora> = [];


  constructor(private router:Router,private servLivros:ControleLivrosService, private servEditora:ControleEditoraService) {
    this.livro = new  Livro();
  }


  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
    // console.log(this.editoras)
  }

  incluir = async () => {
    this.livro.autores = this.autoresForm.split('\n');

    await this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  };
}

<main class="container">
    <h2>Dados dos Livros</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título</label>
        <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required="">
      </div>
  
      <div class="form-group">
        <label for="resumo">Resumo</label>
        <textarea id="resumo" class="form-control" required [(ngModel)]="livro.resumo" name="resumo" required=""></textarea>
      </div>
  
      <div class="form-group">
        <label for="editora">Editora</label>
        <select id="editora" class="form-control" required [(ngModel)]="livro.codEditora" name="editora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
  
      <div class="form-group">
        <label for="autores">Autores</label>
        <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores" required=""></textarea>
      </div>
  
      <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
  </main>

// clientes/livros-next/pages/LivroDados.tsx
import type {NextPage} from "next";
import React, {useState} from "react";
import ControleEditora from "@/classes/controle/ControleEditora";
import {router} from "next/client";
import {Menu} from "../componentes/Menu";
import controleLivros from "@/classes/controle/ControleLivros";
import styles from '@/styles/Home.module.css'

const controleEditora = new ControleEditora()


const LivroDados: NextPage = () => {

    //metodo que pega o array de editora e modifica colocando value e text
    const opcoes = controleEditora.getEditoras().map((editora) => ({
        value: editora.codEditora,
        text: editora.nome
    }));
    //Defini as States inicial
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);


    //redirecionar
    const navigate = (pagina: string) => router.push(pagina);

    const tratarCombo = (evento: any) => {
        const numerointeiro = parseInt(evento.target.value)
        setCodEditora(numerointeiro)
    }

    const incluir = (evento: any) => {
        evento.preventDefault();
        const livro = {
            _id: null,
            codEditora: codEditora,
            titulo: titulo,
            resumo: resumo,
            autores: autores.split("\n")
        };

        incluirLivro(livro);
    };

    const incluirLivro = async (livro: any) => {
        controleLivros.incluir(livro)
            .then(()=>{
                navigate("/LivroLista")
            })
    };


    return (
        <>
            <Menu/>
            
            <main className='container'>
                <h1>Dados do Livro</h1>
                <form onSubmit={incluir} method='post'>
                    <div className="form-group mb-3">
                        <label htmlFor="titulo">Titulo</label>
                        <input
                            type="text"
                            className="form-control"
                            id="titulo"
                            name='titulo'
                            onChange={(evento) => setTitulo(evento.target.value)}required/>
                    </div>

                    <div className="form-group mb-3">
                        <label htmlFor="resumo">Resumo</label>
                        <textarea
                            className="form-control"
                            id="resumo"
                            name='resumo'
                            onChange={(evento) => setResumo(evento.target.value)}required
                        ></textarea>
                    </div>

                    <div className="form-group mb-3">
                        <label htmlFor="editora">Editora</label>
                        <select className="form-control" id="editora" name='editora'
                                onChange={(evento) => tratarCombo(evento)}>
                            {opcoes.map((opcao) => (
                                <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                            ))}
                        </select>
                    </div>

                    <div className="form-group mb-3">
                        <label htmlFor="autores">Autores</label>
                        <textarea
                            className="form-control"
                            id="autores"
                            name='autores'
                            onChange={(evento) => setAutores(evento.target.value)}required
                        ></textarea>
                    </div>

                    <button type="submit" className="btn btn-primary">Salvar Dados</button>
                </form>
            </main>
        </>
    )
}

export default LivroDados;
