// clientes/livros-react/src/LivroDados.js
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleEditora from './controle/ControleEditora';
import ControleLivros from './controle/ControleLivros';

const LivroDados = () => {

  const controleLivro = new ControleLivros();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map(editora => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes.length > 0 ? opcoes[0].value : '');

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();

    const autoresArray = autores.split('\n').map(autor => autor.trim());

    const novoLivro = {
      codigo: 0,
      titulo: titulo,
      resumo: resumo,
      autores: autoresArray,
      codEditora: codEditora,
    };

    controleLivro.incluir(novoLivro).then(() => {
      navigate('/livros');
    });
  };

  return (
    <main className='container'>
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className='form-group mb-3'>
          <label htmlFor='titulo'>Título</label>
          <input 
            type='text'
            id='titulo'
            className='form-control'
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}required
          />
        </div>
        <div className='form-group mb-3'>
          <label htmlFor='resumo'>Resumo</label>
          <textarea 
            id='resumo'
            className='form-control'
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}required
          />
        </div>
        <div className='form-group mb-3'>
          <label htmlFor='editora'>Editora</label>
          <select 
            id='editora'
            className='form-control'
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
            </select>
        </div>
        <div className='form-group mb-3'>
          <label>Autores</label>
          <textarea 
            id='autores'
            className='form-control'
            value={autores}
            onChange={(e) => setAutores(e.target.value)}required
          />
        </div>
        
        <button type='submit' className='btn btn-primary'>
          Salvar Dados
        </button>
      </form>
    </main>
  );
};

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import {Component, OnInit} from '@angular/core';
import {Livro} from "../livro";
import {ControleEditoraService} from "../controle-editora.service";
import {ControleLivrosService} from "../controle-livros.service";
import {Editora} from "../editora";
import {Router} from "@angular/router";

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent implements OnInit{
  livro : Livro;
  autoresForm: string = '';
  public editoras:Array<Editora> = [];


  constructor(private router:Router,private servLivros:ControleLivrosService, private servEditora:ControleEditoraService) {
    this.livro = new  Livro();
  }


  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
    // console.log(this.editoras)
  }

  incluir = async () => {
    this.livro.autores = this.autoresForm.split('\n');

    await this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  };
}

<main class="container">
    <h2>Dados dos Livros</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título</label>
        <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required="">
      </div>
  
      <div class="form-group">
        <label for="resumo">Resumo</label>
        <textarea id="resumo" class="form-control" required [(ngModel)]="livro.resumo" name="resumo" required=""></textarea>
      </div>
  
      <div class="form-group">
        <label for="editora">Editora</label>
        <select id="editora" class="form-control" required [(ngModel)]="livro.codEditora" name="editora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
  
      <div class="form-group">
        <label for="autores">Autores</label>
        <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores" required=""></textarea>
      </div>
  
      <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
  </main>
